### PR TITLE
Enable cne

### PR DESCRIPTION
**Pull request by Astridxx**

### CODE REVIEW

**Comment by feroxx** [comment]
what is that flags really? any bug fix or adding new feature?
and im building userdebug so ifneqis for me :)

**Comment by Astridxx** [comment]
BOARD_USES_QCNE without persist.cne.feature=1 will not work 

MALLOC_SVELTE mobile data memory opens

**Comment by feroxx** [comment]
what is qcne actually? i really dont know about it.

**Comment by Astridxx** [comment]
https://www.qualcomm.com/news/onq/2013/07/02/qualcomms-cne-bringing-smarts-3g4g-wi-fi-seamless-interworking

**Comment by Astridxx** [comment]
Probably makes the network stable

**Pull request closed without merging**
